# Generated by Django 4.1.3 on 2022-12-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
    ]
