# Generated by Django 4.1.3 on 2022-12-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clase.clase')),
            ],
            options={
                'db_table': 'familia',
            },
        ),
    ]
